version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: /frontend
  schedule:
    interval: monthly
  groups:
    minor-bumps:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: pip
  directory: /encoder
  schedule:
    interval: monthly
  groups:
    minor-bumps:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: cargo
  directory: /backend
  schedule:
    interval: monthly
  groups:
    minor-bumps:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: docker
  directory: /backend
  schedule:
    interval: monthly
- package-ecosystem: docker
  directory: /encoder
  schedule:
    interval: monthly
- package-ecosystem: docker
  directory: /frontend
  schedule:
    interval: monthly
