version: 2
updates:
- package-ecosystem: github-actions
  assignees:
    - shish
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: npm
  assignees:
    - shish
  directory: /frontend
  schedule:
    interval: monthly
  groups:
    bumps:
      patterns:
      - '*'
- package-ecosystem: pip
  assignees:
    - shish
  directory: /encoder
  schedule:
    interval: monthly
  groups:
    bumps:
      patterns:
      - '*'
- package-ecosystem: cargo
  assignees:
    - shish
  directory: /backend
  schedule:
    interval: monthly
  groups:
    bumps:
      patterns:
      - '*'
- package-ecosystem: docker
  assignees:
    - shish
  directory: /backend
  schedule:
    interval: monthly
- package-ecosystem: docker
  assignees:
    - shish
  directory: /encoder
  schedule:
    interval: monthly
- package-ecosystem: docker
  assignees:
    - shish
  directory: /frontend
  schedule:
    interval: monthly
