services:
  frontend:
    build: ./frontend
    ports:
      - "2002:3000"

  backend:
    build: ./backend
    ports:
      - "2001:2001"
    volumes:
      - ${MEDIA_PATH:-./media}/processed:/media/processed:ro

  encoder:
    build: ./encoder
    user: "1000"
    volumes:
      - ${MEDIA_PATH:-./media}/source:/media/source:ro
      - ${MEDIA_PATH:-./media}/processed:/media/processed:rw
